language: node_js
node_js:
  - '0.10.26'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install -f'
